# Generated by Django 4.1.7 on 2023-02-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('house_type', models.CharField(choices=[('Terrace', 'Terrace'), ('Semi-D', 'Semi-Detached'), ('Bungalow', 'Bungalow'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Condominium', 'Condominium'), ('Penthouse', 'Penthouse')], default='Apartment', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Disclosed')], default='N', max_length=2)),
                ('birth_date', models.DateField(verbose_name='date of birth')),
                ('description', models.CharField(max_length=300)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human', to='sitecat.home')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('birth_date', models.DateField(verbose_name='date of birth')),
                ('description', models.CharField(max_length=300)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='sitecat.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='sitecat.human')),
            ],
        ),
    ]
