# Generated by Django 4.1.7 on 2023-03-15 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecat.breed'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecat.human'),
        ),
        migrations.AlterField(
            model_name='human',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecat.home'),
        ),
    ]
