# Generated by Django 4.1.7 on 2023-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecat', '0002_alter_breed_description_alter_cat_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
