# Generated by Django 4.1.7 on 2023-03-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecat', '0003_alter_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Disclosed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Disclosed')], default='N', max_length=1),
        ),
    ]
