# Generated by Django 4.1.7 on 2023-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecat', '0006_alter_cat_gender_alter_human_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='house_type',
            field=models.CharField(choices=[('TERRACE', 'Terrace'), ('SEMID', 'Semi Detached'), ('BUNGALOW', 'Bungalow'), ('FLAT', 'Flat'), ('APARTMENT', 'Apartment'), ('CONDOMINIUM', 'Condominium'), ('PENTHOUSE', 'Penthouse')], default='APARTMENT', max_length=20),
        ),
    ]
