# Generated by Django 3.2.18 on 2023-03-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecat', '0007_alter_home_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='house_type',
            field=models.CharField(choices=[('Terrace', 'Terrace'), ('Semi-D', 'Semi-Detached'), ('Bungalow', 'Bungalow'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Condominium', 'Condominium'), ('Penthouse', 'Penthouse')], default='Apartment', max_length=20),
        ),
    ]
